# Generated by Django 4.0.6 on 2022-07-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_1', models.CharField(blank=True, max_length=200, null=True)),
                ('data_2', models.CharField(blank=True, max_length=200, null=True)),
                ('data_3', models.CharField(blank=True, max_length=200, null=True)),
                ('data_4', models.CharField(blank=True, max_length=200, null=True)),
                ('data_5', models.CharField(blank=True, max_length=200, null=True)),
                ('data_6', models.CharField(blank=True, max_length=200, null=True)),
                ('data_7', models.CharField(blank=True, max_length=200, null=True)),
                ('data_8', models.CharField(blank=True, max_length=200, null=True)),
                ('data_9', models.CharField(blank=True, max_length=200, null=True)),
                ('data_10', models.CharField(blank=True, max_length=200, null=True)),
                ('data_11', models.CharField(blank=True, max_length=200, null=True)),
                ('data_12', models.CharField(blank=True, max_length=200, null=True)),
                ('data_13', models.CharField(blank=True, max_length=200, null=True)),
                ('data_14', models.CharField(blank=True, max_length=200, null=True)),
                ('data_15', models.CharField(blank=True, max_length=200, null=True)),
                ('data_16', models.CharField(blank=True, max_length=200, null=True)),
                ('data_17', models.CharField(blank=True, max_length=200, null=True)),
                ('data_18', models.CharField(blank=True, max_length=200, null=True)),
                ('data_20', models.CharField(blank=True, max_length=200, null=True)),
                ('data_21', models.CharField(blank=True, max_length=200, null=True)),
                ('data_22', models.CharField(blank=True, max_length=200, null=True)),
                ('data_23', models.CharField(blank=True, max_length=200, null=True)),
                ('data_24', models.CharField(blank=True, max_length=200, null=True)),
                ('data_25', models.CharField(blank=True, max_length=200, null=True)),
                ('data_26', models.CharField(blank=True, max_length=200, null=True)),
                ('data_27', models.CharField(blank=True, max_length=200, null=True)),
                ('data_28', models.CharField(blank=True, max_length=200, null=True)),
                ('data_29', models.CharField(blank=True, max_length=200, null=True)),
                ('data_30', models.CharField(blank=True, max_length=200, null=True)),
                ('data_31', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
