# Generated by Django 4.0.6 on 2022-07-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_productdata_data_31'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='data_19',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
