# Generated by Django 4.0.6 on 2022-07-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_productdata_data_19'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='data_30',
            new_name='data_31',
        ),
        migrations.AddField(
            model_name='productdata',
            name='data_32',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdata',
            name='data_33',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productdata',
            name='data_34',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
