# Generated by Django 4.0.6 on 2022-07-08 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_data_30_productdata_data_31_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdata',
            old_name='data_31',
            new_name='data_30',
        ),
    ]
